Repository ManiVaultStudio/core, pull requests merged in 2024-04, with the labels that each got.

#564 Make initial working implementation of TextData
  ManiVault/src/plugins/TextData/CMakeLists.txt
  ManiVault/src/plugins/TextData/src/InfoAction.cpp
  ManiVault/src/plugins/TextData/src/InfoAction.h
  ManiVault/src/plugins/TextData/src/TextData.cpp
  ManiVault/src/plugins/TextData/src/TextData.h
  ManiVault/src/plugins/TextData/src/TextData.json
Labels: enhancement

#558 Improve options action performance for large options database and add list view
  ManiVault/cmake/CMakeMvSourcesPublic.cmake
  ManiVault/src/actions/HorizontalHeaderAction.cpp
  ManiVault/src/actions/HorizontalHeaderAction.h
  ManiVault/src/actions/LabelProxyAction.h
  ManiVault/src/actions/LockingAction.h
  ManiVault/src/actions/ModelFilterAction.cpp
  ManiVault/src/actions/ModelFilterAction.h
  ManiVault/src/actions/ModelSelectionAction.cpp
  ManiVault/src/actions/ModelSelectionAction.h
  ManiVault/src/actions/OptionsAction.cpp
  ManiVault/src/actions/OptionsAction.h
  ManiVault/src/actions/PluginTriggerAction.h
  ManiVault/src/actions/PluginTriggerPickerAction.h
  ManiVault/src/actions/PresetsAction.h
  ManiVault/src/actions/RecentFilesAction.h
  ManiVault/src/actions/SplashScreenAction.h
  ManiVault/src/actions/TableAction.cpp
  ManiVault/src/actions/TableAction.h
  ManiVault/src/actions/TasksListAction.h
  ManiVault/src/actions/TasksTreeAction.h
  ManiVault/src/actions/WidgetActionBadgeOverlayWidget.h
  ManiVault/src/actions/WidgetActionCollapsedWidget.h
  ManiVault/src/actions/WidgetActionContextMenu.h
  ManiVault/src/actions/WidgetActionHighlightWidget.h
  ManiVault/src/actions/WidgetActionLabel.h
  ManiVault/src/actions/WidgetActionMimeData.h
  ManiVault/src/actions/WidgetActionToolButton.h
  ManiVault/src/actions/WidgetActionToolButtonMenu.h
  ManiVault/src/actions/WidgetActionViewWidget.h
  ManiVault/src/actions/WidgetActionWidget.h
  ManiVault/src/models/CheckableStringListModel.cpp
  ManiVault/src/models/CheckableStringListModel.h
  ManiVault/src/plugins/DataHierarchyPlugin/src/DataHierarchyWidget.cpp
Labels: enhancement

#575 Limit signals in numerical actions
  ManiVault/src/actions/DecimalRangeAction.cpp
  ManiVault/src/actions/DecimalRectangleAction.cpp
  ManiVault/src/actions/DecimalRectangleAction.h
  ManiVault/src/actions/IntegralRangeAction.cpp
  ManiVault/src/actions/IntegralRectangleAction.cpp
  ManiVault/src/actions/IntegralRectangleAction.h
  ManiVault/src/actions/NumericalRangeAction.h
  ManiVault/src/actions/RectangleAction.h
Labels: enhancement

#580 Restore PixelSelectionAction modifier key behaviour
  ManiVault/src/actions/PixelSelectionAction.cpp
Labels: bug

#583 Change ADS target output name
  ManiVault/CMakeLists.txt
Labels: bug

#569 Add high-performance datasets model
  ManiVault/cmake/CMakeMvSourcesPublic.cmake
  ManiVault/src/AbstractActionsManager.h
  ManiVault/src/AbstractDataManager.h
  ManiVault/src/Plugin.cpp
  ManiVault/src/RawData.h
  ManiVault/src/Set.cpp
  ManiVault/src/actions/DatasetPickerAction.cpp
  ManiVault/src/actions/DatasetPickerAction.h
  ManiVault/src/actions/OptionAction.cpp
  ManiVault/src/actions/WidgetActionContextMenu.cpp
  ManiVault/src/models/AbstractDatasetsModel.cpp
  ManiVault/src/models/AbstractDatasetsModel.h
  ManiVault/src/models/AbstractTasksModel.cpp
  ManiVault/src/models/DataHierarchyListModel.cpp
  ManiVault/src/models/DataHierarchyTreeModel.cpp
  ManiVault/src/models/DatasetsFilterModel.cpp
  ManiVault/src/models/DatasetsFilterModel.h
  ManiVault/src/models/DatasetsListModel.cpp
  ManiVault/src/models/DatasetsListModel.h
  ManiVault/src/models/RawDataModel.cpp
  ManiVault/src/plugins/DataHierarchyPlugin/src/DataHierarchyWidget.cpp
  ManiVault/src/plugins/DataHierarchyPlugin/src/DataHierarchyWidget.h
  ManiVault/src/plugins/DataPropertiesPlugin/src/DataPropertiesPlugin.cpp
  ManiVault/src/private/ActionsManager.cpp
  ManiVault/src/private/ActionsManager.h
  ManiVault/src/private/DataHierarchyManager.cpp
  ManiVault/src/private/DataManager.cpp
  ManiVault/src/private/DataManager.h
  ManiVault/src/private/MainWindow.cpp
  ManiVault/src/private/PluginManager.cpp
Labels: enhancement

#592 Re-instates RawDataModel::populateFromDataManager() and adds common MV models
  ManiVault/cmake/CMakeMvSourcesPublic.cmake
  ManiVault/src/models/AbstractActionsModel.cpp
  ManiVault/src/models/AbstractActionsModel.h
  ManiVault/src/models/AbstractDataHierarchyModel.cpp
  ManiVault/src/models/AbstractDataHierarchyModel.h
  ManiVault/src/models/AbstractDatasetsModel.cpp
  ManiVault/src/models/AbstractDatasetsModel.h
  ManiVault/src/models/AbstractPluginFactoriesModel.cpp
  ManiVault/src/models/AbstractPluginFactoriesModel.h
  ManiVault/src/models/AbstractPluginsModel.cpp
  ManiVault/src/models/AbstractPluginsModel.h
  ManiVault/src/models/AbstractTasksModel.cpp
  ManiVault/src/models/AbstractTasksModel.h
  ManiVault/src/models/ActionsFilterModel.cpp
  ManiVault/src/models/ActionsFilterModel.h
  ManiVault/src/models/DataHierarchyFilterModel.cpp
  ManiVault/src/models/DataHierarchyFilterModel.h
  ManiVault/src/models/DatasetsFilterModel.cpp
  ManiVault/src/models/DatasetsFilterModel.h
  ManiVault/src/models/LoggingFilterModel.cpp
  ManiVault/src/models/LoggingFilterModel.h
  ManiVault/src/models/LoggingModel.cpp
  ManiVault/src/models/LoggingModel.h
  ManiVault/src/models/NumberOfRowsAction.cpp
  ManiVault/src/models/NumberOfRowsAction.h
  ManiVault/src/models/PluginFactoriesFilterModel.cpp
  ManiVault/src/models/PluginFactoriesFilterModel.h
  ManiVault/src/models/PluginsFilterModel.cpp
  ManiVault/src/models/PluginsFilterModel.h
  ManiVault/src/models/RawDataFilterModel.cpp
  ManiVault/src/models/RawDataFilterModel.h
  ManiVault/src/models/RawDataModel.cpp
  ManiVault/src/models/RawDataModel.h
  ManiVault/src/models/SelectionsFilterModel.cpp
  ManiVault/src/models/SelectionsFilterModel.h
  ManiVault/src/models/SelectionsModel.cpp
  ManiVault/src/models/SelectionsModel.h
  ManiVault/src/models/SortFilterProxyModel.cpp
  ManiVault/src/models/SortFilterProxyModel.h
  ManiVault/src/models/StandardItemModel.cpp
  ManiVault/src/models/StandardItemModel.h
  ManiVault/src/models/TasksFilterModel.cpp
  ManiVault/src/models/TasksFilterModel.h
  ManiVault/src/plugins/DataHierarchyPlugin/CMakeLists.txt
  ManiVault/src/plugins/DataHierarchyPlugin/src/DataHierarchyWidget.cpp
  ManiVault/src/plugins/DataHierarchyPlugin/src/DataHierarchyWidget.h
  ManiVault/src/plugins/DataHierarchyPlugin/src/DatasetsFilterModel.cpp
  ManiVault/src/plugins/DataHierarchyPlugin/src/DatasetsFilterModel.h
  ManiVault/src/plugins/DataHierarchyPlugin/src/DatasetsModel.cpp
  ManiVault/src/plugins/DataHierarchyPlugin/src/DatasetsModel.h
  ManiVault/src/plugins/DataHierarchyPlugin/src/StatisticsAction.cpp
  ManiVault/src/plugins/DataHierarchyPlugin/src/StatisticsAction.h
Labels: bug, enhancement

#588 Disconnect signals when a previous clusters dataset is present
  ManiVault/src/plugins/ClusterData/src/ClustersAction.cpp
Labels: bug
