Repository ManiVaultStudio/core, pull requests merged in 2024-05, with the labels that each got.

#601 Split up multi-line messages into segments and the handle these seperately
  ManiVault/src/util/Logger.cpp
Labels: bug

#604 Send both signals on web bridge ready and page fully loaded
  ManiVault/src/widgets/WebWidget.cpp
  ManiVault/src/widgets/WebWidget.h
Labels: amendment

#614 Rebase from master
  conanfile.py
Labels: enhancement

#616 Fix options action crashing due to multiple emits being sent
  ManiVault/src/models/CheckableStringListModel.cpp
Labels: bug
