Repository ManiVaultStudio/core, pull requests merged in 2024-11, with the labels that each got.

#716 Link statically to QuaZip
  ManiVault/CMakeLists.txt
  ManiVault/cmake/CMakeQuaZipSymlink.cmake
Labels: enhancement, core, macOS, Windows, Linux

#723 Tix toggle action drag and drop
  ManiVault/cmake/CMakeMvSourcesPublic.cmake
  ManiVault/src/actions/ToggleAction.cpp
  ManiVault/src/actions/WidgetAction.cpp
  ManiVault/src/actions/WidgetAction.h
  ManiVault/src/actions/WidgetActionContextMenu.cpp
  ManiVault/src/actions/WidgetActionDrag.cpp
  ManiVault/src/actions/WidgetActionDrag.h
  ManiVault/src/actions/WidgetActionLabel.cpp
  ManiVault/src/actions/WidgetActionMimeData.cpp
Labels: bug, enhancement

#725 Fix malformed clusters crash
  ManiVault/src/util/MeanShift.cpp
Labels: bug

#728 Fix manager destruction
  ManiVault/src/AbstractActionsManager.h
  ManiVault/src/AbstractDataHierarchyManager.h
  ManiVault/src/AbstractDataManager.h
  ManiVault/src/AbstractEventManager.h
  ManiVault/src/AbstractHelpManager.h
  ManiVault/src/AbstractManager.h
  ManiVault/src/AbstractPluginManager.h
  ManiVault/src/AbstractProjectManager.h
  ManiVault/src/AbstractSettingsManager.h
  ManiVault/src/AbstractTaskManager.h
  ManiVault/src/AbstractWorkspaceManager.h
  ManiVault/src/CoreInterface.h
  ManiVault/src/Task.cpp
  ManiVault/src/actions/StatusBarAction.cpp
  ManiVault/src/actions/WidgetAction.cpp
  ManiVault/src/models/AbstractPluginsModel.cpp
  ManiVault/src/private/ActionsManager.cpp
  ManiVault/src/private/ActionsManager.h
  ManiVault/src/private/Core.cpp
  ManiVault/src/private/Core.h
  ManiVault/src/private/DataHierarchyManager.cpp
  ManiVault/src/private/DataHierarchyManager.h
  ManiVault/src/private/DataManager.cpp
  ManiVault/src/private/DataManager.h
  ManiVault/src/private/DockAreaTitleBar.cpp
  ManiVault/src/private/DockManager.h
  ManiVault/src/private/EventManager.cpp
  ManiVault/src/private/EventManager.h
  ManiVault/src/private/HelpManager.cpp
  ManiVault/src/private/HelpManager.h
  ManiVault/src/private/PluginManager.cpp
  ManiVault/src/private/PluginManager.h
  ManiVault/src/private/ProjectManager.cpp
  ManiVault/src/private/ProjectManager.h
  ManiVault/src/private/SettingsManager.cpp
  ManiVault/src/private/SettingsManager.h
  ManiVault/src/private/TaskManager.cpp
  ManiVault/src/private/TaskManager.h
  ManiVault/src/private/WorkspaceManager.cpp
  ManiVault/src/private/WorkspaceManager.h
  ManiVault/src/widgets/ViewPluginLearningCenterOverlayWidget.cpp
Labels: bug, enhancement
